var wisdomList = 
["Calling something overrated is just saying you disagree with the popular opinion.",
"If you failed at something nobody has ever failed before, then you have accomplished something nobody has ever accomplished.", 
"If EA suffers big enough losses from the backlash of Battlefront 2, and it all started because some guy couldn't unlock Vader, this will be the second time Anakin brought balance to something.",
"Gummy worms have more bones in them than actual worms.",
"The syllables in “on your mark, get set, go” are a countdown",
"Lamps in Videogames use real electricity.",
"On a galactic scale, amber and pearl are far rarer than gold and diamonds because they require life.",
"There is no physical evidence to say that today is Wednesday, we all just have to trust that someone has kept count since the first one ever.",
"Baby Yoda's first word probably came after his second word",
"Replying 'k' in morse '-.-', has the same passive aggressive tone",
"If you think a new television's picture looks mind blowing in an ad on yours, you don't need a new television.",
"There can be a genius that is just not known due to poverty",
"You are probably the best at something, even if it hasn't been invented yet",
"People's names are just specific sounds you make with your mouth to call someone's attention (suggested by :tomato:)",
"You are probably the worst at something, even if it hasn't been invented yet",
"Error: User above is an idiot",
"Error: User above is cute UwU",
"The meaning of some words and emojis change as you get older ('Daddy' and :eggplant:)",
"EMPTY sounds the same if you take out E; E and P; or even E P and Y.",
"We are all addicted to water and food, and the withdrawal symptom is death.",
"You can be blinded by the light and you can also be blinded by the lack of light.",
"Choosing a username that doesn't require you to add a number is the closest we'll come to an original thought",
"If humans were as intelligent as we think we are, we would agree on more things.",
"The universe is so unimaginably big that, theoretically, somewhere out there, Star Wars and Luke Skywalker could actually exist.",
"Bread and butter is a perfectly acceptable side, but the idea of a butter sandwich would disgust most people",
"Smartphones arent smart f||ucking|| dumb b||itches||",
"It's easier to make another $100,000 if you already have $1,000,000, but it's not easy to make another $10 if you only have $100.",
"The 3 wise men are the first persons to ever Christmas shop",
"Chewing ice is drinking water, but having to work harder for it.",
"When something blows up, it's doing really good, but when it bombs, it's doing horribly. However, when something is the bomb, its great, but it blowing up in your face is bad.",
"Satan and Santa are both red and have a realm for themselves.",
"Satan probably wouldnt treat sinners badly.",
"Dumb people are so arrogant because they never experience the humbling sensation of learning something new and then feel the 'click' in their head when they understand it.",
"The same things you would die to get are possibly the same things you’d live to keep.",
"Candle companies make various candles hoping you have money to burn.",
"Everything in the universe is either banana or not banana",
"claustrophobic people are fine with their brains being trapped in their skull",
"Randomly hearing your favorite song on the radio is more satisfying than playing it directly from your own device.",
"Maybe plants are really farming us, giving us oxygen until we eventually expire and turn into mulch which they can consume...",
"Theme parks can snap a crystal clear picture of you on a roller coaster at 70 mph, but bank cameras can't get a clear shot of a robber standing still.",
"Lawyers hope you get sued, doctors hope you get sick, cops hope you're criminal, mechanics hope you have car trouble, but only a thief wishes prosperity for you.",
"As a kid my parents taught me to not believe everything I see on TV, now I have to teach them to not believe everything they see on Facebook.",
"The Olympics should have a 'For Fun' section at the end of all the games so all the athletes can try different sports.",
"If someone offered to pay for my food and rent for the next 18 years, I'd do anything they ask of me. But I complained every time I took the trash out while living at my parent's house.",
"Aliens invaded the Moon on July 20th, 1969.",
"When you say 'Forward' or 'Back', your lips move in those directions.",
"I've woken up over 10,000 times and I'm still not used to it",
"When a company offers me a better price after I cancel their subscription, they're just admitting they were overcharging me.",
"Christmas feels more like a deadline than a holiday.",
"'DO NOT TOUCH' would probably be a really unsettling thing to read in braille.",
"After years of disliking the way i look, only now i realize I'm not ugly, I'm just not my type.",
"We talk about Ancient Romans like they were basically all the same, but the civilization lasted almost 1000 years. That's like saying people in 2016 and 1016 are basically the same.",
"People who are goodlooking but have terrible personalities are basically real life click baits.",
"When people think about travelling to the past, they worry about accidentally changing the present, but no one in the present really thinks they can radically change the future.",
"When I bake bread, I give thousands of yest organisms false hope by feeding them sugar, before ruthlessly baking them to death in an oven and eating their corpses.",
"My dog understand several human words. I don’t understand any dog barks. He may be smarter than me.",
"Nothing is on fire, fire is on things.",
"If Google matched people up by their browsing history, it could be the greatest online dating website of all time.",
"If aliens come to earth, we have to explain why we made dozens of movies in which we fight and kill them.",
"Every time a character dies on a TV show I just feel bad for the actor who pretty much just got fired in front of us.",
"I don't know a single person who would want a thinner phone over a few hours of extra battery life.",
"We stick kids in classrooms 8 hours a day, give them another few hours of homework, actively discourage them from playing outside, and then wonder why kids today are so out of shape.",
"History classes are only going to get longer and harder as time goes on.",
"Sleep should be rolled over. Like 'Oh, you got 20 hours of sleep today? Cool man, you don't need sleep for the next three days!'",
"If cats had wings,they'd still just lay there.",
"1984-2000 seems a very long time compared to 2000-2016.",
"The fact that I can't recognize my co-workers outside of uniform 85% of the time, tells me superman knows exactly what he's doing.",
"Taxes are like a subscription to your Country that you can't cancel, no matter how bad the service gets.",
"Some women want their outfit to be noticed. As a male, I would prefer nobody noticing it so I can still wear it the next day. ||Also, some females also want this, it's just popular opinion||",
"When Sweden is playing Denmark, it is SWE-DEN. The remaining letters, not used, is DEN-MARK.",
"Car horns should only be allowed to be in pitches C, E, and G, so whenever two people honk at the same time it will be in harmony and traffic jams will sound like symphonies.",
"I'm glad dogs can't read the 'no dogs allowed' signs so they don't feel sad and left out.",
"Your stomach thinks that all potatoes are mashed.",
"I am 100% confident that if I ever hit a kid with my car, it will be because I'm staring at my speedometer in a school zone.",
"I never realize how explicit my music is until my parents hear it in the car.",
"Clapping is just hitting your hands together repeatedly because you like something.",
"When jogging, we put on special clothes so people don't think we are running from or to something.",
"In order to fall asleep, you have to pretend to be asleep.",
"Every time I check my pockets for my wallet, keys, and phone, I do 25% of the macarena.",
"When the older generations says this generation is terrible, they're really saying they sucked as parents.",
"We insult people by calling them a||aa||holes, d||uc||ks & pus||cat||s - some of the most important and essential body parts. We should be calling people we don't like an appendix.",
"Why do people say 'tuna fish' when they don't say 'beef mammal' or 'chicken bird'?",
"If a stranger insults me, I'l probably ignore it, as their opinion is meaningless. If a stranger compliments me, I'll probably treasure it, as their opinion is important.",
"The object of golf is to play the least amout of golf.",
"If opposites attract, I should be dating a gorgeous, billionaire supermodel that has a loving family.",
"Using solar panels to power an air conditioning unit is like using the Sun's power against itself.",
"Brushing your teeth is the only time you clean your skeleton.",
"Apple has anorexia: it is obsessed with thinness which leads it to remove things people actually need.",
"Students are stereotypically viewed as being lazy, but I worked ten times harder as a student than I do in my career now.",
"Depression is like being in an emotionally abusive relationship with your brain",
"Whenever you dig up dirt or a rock, that could be the first time it has seen the sun in millions of years.||Unless you dig it out at night||",
"The Hobbit was a book about the dangers of greed. The Hobbit films were ruined because of greed.",
"Being first in a youtube video is hard, but being last is harder",
"You don't actually know your birthday, you're just relying on your parents word",
"Dry humor implies there is moist humor."];

function showerThought(){
    var l = wisdomList.length;
    var r = Math.floor(Math.random() * (l - 0) ) + 0;
    console.log(r)
    return wisdomList[r];
};

exports.showerThought = showerThought;
